In [ ]:
import pandas as pd
import numpy as np

In [ ]:
! apt-get install git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 45 not upgraded.

In [ ]:
 https://github.com/"JADESOLA-O"/"https://github.com/JADESOLA-O/Tag-along"

SyntaxError: invalid syntax (<ipython-input-39-1636d64bd970>, line 1)

# New Section

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
#copy the file path
df = pd.read_csv("/content/FoodBalanceSheets_E_Africa_NOFLAG.csv", encoding = "latin-1")
#df('FoodBalanceSheets_E_Africa_NOFLAG.csv', index = False)

In [ ]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [ ]:
df.shape

(60943, 12)

In [ ]:
df.columns

Index(['Area Code', 'Area', 'Item Code', 'Item', 'Element Code', 'Element',
       'Unit', 'Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     60943 non-null  int64
 1   Area          60943 non-null  object
 2   Item Code     60943 non-null  int64
 3   Item          60943 non-null  object
 4   Element Code  60943 non-null  int64
 5   Element       60943 non-null  object
 6   Unit          60943 non-null  object
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB

In [ ]:

grouped = df.groupby('Area')['Y2017'].sum()

# Find the area with the highest sum in 2017
highest_sum_area = grouped.idxmax()

print(f"The Area with the highest sum in 2017 is: {highest_sum_area}")

The Area with the highest sum in 2017 is: Nigeria

In [ ]:
unique_countries = df['Area'].nunique()
unique_countries

49

In [ ]:
# count missing values(NANs) in each column of dataset
df.isna().sum()

Area Code          0
Area               0
Item Code          0
Item               0
Element Code       0
Element            0
Unit               0
Y2014           1589
Y2015           1548
Y2016           1535
Y2017           1506
Y2018           1436
dtype: int64

In [ ]:
def missing_vals(df):return pd.DataFrame({"no_of_missing_vals": df.isna().sum(),"%_of_missing_vals": round((df.isna().sum() / len(df)) * 100, 2), })

missing_vals(df)

              no_of_missing_vals  %_of_missing_vals
Area Code                      0               0.00
Area                           0               0.00
Item Code                      0               0.00
Item                           0               0.00
Element Code                   0               0.00
Element                        0               0.00
Unit                           0               0.00
Y2014                       1589               2.61
Y2015                       1548               2.54
Y2016                       1535               2.52
Y2017                       1506               2.47
Y2018                       1436               2.36

In [ ]:
array = ([[94, 89, 63],
           [93, 92, 48,],
          [92, 94,56]])

In [ ]:
my_tuppy = (1,2,5,8)

my_tuppy[2] = 6

TypeError: 'tuple' object does not support item assignment

In [ ]:
correlations = df[['Element Code', 'Y2017']].corr()['Element Code']
# Remove the correlation of 'Element Code' with itself
correlations = correlations.drop('Element Code')

# Now find the year with the least correlation
year_with_least_correlation = correlations.idxmin()
year_with_least_correlation

'Y2017'

In [ ]:

# Group by 'Area' and sum 'Y2017'
grouped = df.groupby('Area')['Y2017'].sum()

# Sort the sums
sorted_sums = grouped.sort_values()

# Find the 7th lowest sum
seventh_lowest_area = sorted_sums.iloc[6]  # since Python uses 0-based indexing
seventh_lowest_area_name = sorted_sums.index[6]
print(f"The year with the least correlation with 'Element Code' is {seventh_lowest_area} with a correlation coefficient of {seventh_lowest_area_name}.")

The year with the least correlation with 'Element Code' is 19102.77 with a correlation coefficient of Guinea-Bissau.

In [ ]:
correlations = {}
for year in ['Y2014', 'Y2015', 'Y2016', 'Y2017']:
    correlations[year] = df['Element Code'].corr(df[year])

# Find the year with the minimum correlation
min_corr_year = min(correlations, key=correlations.get)
min_corr_value = correlations[min_corr_year]

print(f"The year with the least correlation with 'Element Code' is {min_corr_year} with a correlation coefficient of {min_corr_value}.")

The year with the least correlation with 'Element Code' is Y2016 with a correlation coefficient of 0.023443997584961424.

In [ ]:
S = [['him', 'sell'], [90,28,43]]
S[0][1][1]

'e'

In [ ]:
#statistical analysis of all numerical dataset
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [ ]:
# Filter the DataFrame for rows where 'Element' is 'Stock Variation'
stock_variation_df = df[df['Element'] == 'Stock Variation']

# Sum the values across the years for these rows
yearly_sums = stock_variation_df[['Y2014', 'Y2015', 'Y2016', 'Y2017']].sum()

# Determine the year with the highest sum
highest_year = yearly_sums.idxmax()

print(f"The year with the highest sum of Stock Variation is: {highest_year}")

The year with the highest sum of Stock Variation is: Y2014

In [ ]:
# Filter the DataFrame for rows where the 'Area' is 'Madagascar' and the 'Element' is 'Protein supply quantity (g/capita/day)'
madagascar_protein_df = df[(df['Area'] == 'Madagascar') & (df['Element'] == 'Protein supply quantity (g/capita/day)')]
madagascar_protein_df

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
30718,129,Madagascar,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,44.45,43.26,43.35,43.94,44.17
30721,129,Madagascar,2903,Vegetal Products,674,Protein supply quantity (g/capita/day),g/capita/day,35.43,34.04,33.96,34.47,34.81
30724,129,Madagascar,2941,Animal Products,674,Protein supply quantity (g/capita/day),g/capita/day,9.02,9.23,9.38,9.47,9.36
30740,129,Madagascar,2905,Cereals - Excluding Beer,674,Protein supply quantity (g/capita/day),g/capita/day,27.97,27.26,27.38,27.97,28.19
30756,129,Madagascar,2511,Wheat and products,674,Protein supply quantity (g/capita/day),g/capita/day,2.09,2.14,2.53,2.88,3.15
...,...,...,...,...,...,...,...,...,...,...,...,...
32113,129,Madagascar,2769,"Aquatic Animals, Others",674,Protein supply quantity (g/capita/day),g/capita/day,0.01,0.01,0.00,0.00,0.00
32123,129,Madagascar,2775,Aquatic Plants,674,Protein supply quantity (g/capita/day),g/capita/day,0.00,0.00,0.00,0.00,0.00
32133,129,Madagascar,2928,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.02,0.02,0.02,0.02,0.02
32142,129,Madagascar,2680,Infant food,674,Protein supply quantity (g/capita/day),g/capita/day,0.00,0.00,0.00,0.00,0.00
32152,129,Madagascar,2899,Miscellaneous,674,Protein supply quantity (g/capita/day),g/capita/day,0.01,0.01,0.01,0.01,0.01

In [ ]:
# Sum up the values in the column that contains the protein supply data

total_protein = madagascar_protein_df['Y2015'].sum()

print(f"Total Protein supply in Madagascar: {total_protein}")

Total Protein supply in Madagascar: 173.04999999999998

In [ ]:
processing_2017 = df[df['Element'] == 'Processing']
sum_processing_2017 = processing_2017.groupby('Element')['Y2017'].sum()
print(sum_processing_2017)

Element
Processing    292836.0
Name: Y2017, dtype: float64